Update deploy.yml added qg

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,6 +39,36 @@ jobs:
             -Dsonar.host.url=http://13.232.125.253:9000 \
             -Dsonar.login=$SONAR_TOKEN
 
+      - name: Wait for SonarQube Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          echo "Waiting for SonarQube analysis to complete..."
+          projectKey="My-Project"
+          ceTaskUrl=$(curl -s -u $SONAR_TOKEN: "http://13.232.125.253:9000/api/ce/component?component=$projectKey" | jq -r '.queue[0].url')
+
+          # Poll the CE task until it completes
+          status="PENDING"
+          while [ "$status" != "SUCCESS" ]; do
+            sleep 5
+            status=$(curl -s -u $SONAR_TOKEN: "$ceTaskUrl" | jq -r '.task.status')
+            echo "Current analysis status: $status"
+            if [[ "$status" == "FAILED" ]]; then
+              echo "SonarQube analysis failed"
+              exit 1
+            fi
+          done
+
+          analysisId=$(curl -s -u $SONAR_TOKEN: "$ceTaskUrl" | jq -r '.task.analysisId')
+
+          qualityGateStatus=$(curl -s -u $SONAR_TOKEN: "http://13.232.125.253:9000/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
+          echo "Quality Gate Status: $qualityGateStatus"
+
+          if [ "$qualityGateStatus" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
+          fi
+
       - name: Upload WAR to Artifactory
         env:
           ARTIFACTORY_URL: http://13.232.125.253:8082/artifactory
